spring:
  application:
    name: authify-backend


  datasource:
    url: jdbc:mysql://localhost:3306/security_db_demo
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: ${SMTP_HOST}
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            trust: "*" # this is only for testing. don't use this in production.
          starttls:
            enable: true
          from: madhubhashana655@gmail.com
    protocol: smtp




server:
  servlet:
    context-path: /api/v1.0
  error:
    include-message: always
    include-binding-errors: always


jwt:
  secret: Y2hhbmdlVGhpc1RvQVNlY3VyZVNlY3JldEtleTEyMzQ1Njc4OQ==
